/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package server

import io.javalin.Javalin
import io.javalin.core.validation.JavalinValidation
import server.PlayerSocket.Companion.playerParam
import java.util.*

fun main() {
    JavalinValidation.register(UUID::class.java, UUID::fromString)

    val app = Javalin.create { config ->
        config.enableCorsForAllOrigins()
        config.defaultContentType = "application/json"
        config.wsFactoryConfig { it.policy.idleTimeout = 3*60*60*1000 }
//        config.enableDevLogging()
    }

    app.ws(playerParam, Game.endpoint)

    app.start()
}
